### ISSUE TITLE
Where can i get access token?

### ISSUE THREAD

**Issue by vega0** [Kolsha/VK#13]
Where can i get VK API access token, need to know step by step.

**Comment by TodNaz** [comment]
В [Быстром старте](https://dev.vk.com/api/getting-started), в абзаце [авторизация пользователя](https://dev.vk.com/api/getting-started#%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F) написано:

> ВКонтакте — социальная сеть, где есть дружеские связи, настройки приватности и даже черные списки. Многое зависит от того, кто просматривает страницу: кто-то увидит на ней всю ту же информацию, что и владелец, а кто-то — лишь общедоступные данные.

> В API этот принцип сохраняется. Если вы скрыли список своих групп от не-друзей, то и через API ваши не-друзья не должны его увидеть. Поэтому почти все методы требуют авторизации пользователя перед началом работы. Проще говоря, сервер должен знать, кто к нему обращается за информацией, чтобы предоставить ее в том же виде, что и в основной версии сайта.

> В общем случае для идентификации в API используется специальный ключ доступа, который называется access_token.
Токен — это строка из цифр и латинских букв, которую вы передаете на сервер вместе с запросом. Из этой строки сервер получает всю нужную ему информацию. Есть разные способы получения токена, более того, он может быть выдан не только пользователю, но и сообществу, и сразу всему приложению — подробнее об этом вы можете прочитать [здесь](https://dev.vk.com/api/access-token/getting-started).

> Мы воспользуемся самым простым способом ([Implicit flow](https://dev.vk.com/api/access-token/implicit-flow-user)) и получим токен для работы с API из созданного вами на прошлом этапе приложения.

> Откройте новую вкладку в браузере и введите в адресную строку такой запрос:

> https://oauth.vk.com/authorize?client_id=5490057&display=page&redirect_uri=https://oauth.vk.com/blank.html&scope=friends&response_type=token&v=5.131

> Число 5490057 в запросе нужно заменить на API_ID вашего приложения.

> Нажмите Enter. Откроется окно с запросом прав. В нем отображаются название приложения, иконки прав доступа, и ваши имя с фамилией.

> Нажмите Разрешить. вы попадете на новую страницу с предупреждением о том, что токен нельзя копировать и передавать третьим лицам. В адресной строке будет URL [https://oauth.vk.com/blank.html](https://vk.com/away.php?to=https://oauth.vk.com/blank.html), а после # вы увидите дополнительные параметры — access_token, expires_in и user_id. Токен может выглядеть, например, так:

> 51eff86578a3bbbcb5c7043a122a69fd04dca057ac821dd7afd7c2d8e35b60172d45a26599c08034cc40a

> Токен — это ваш ключ доступа. При выполнении определенных условий человек, получивший ваш токен, может нанести существенный ущерб вашим данным и данным других людей. Поэтому очень важно не передавать свой токен третьим лицам.

Типо, оттуда можно вытянуть токен, всё в официальных доках, как не странно) Надеюсь, я не поздно)
