### ISSUE TITLE
json.hpp вылетает

### ISSUE THREAD

**Issue by lexasub** [Kolsha/VK#2]
json.hpp:8190: nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::iter_impl<U>::reference nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::iter_impl<U>::operator*() const [with U = nlohmann::basic_json<>; ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer; nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::iter_impl<U>::reference = nlohmann::basic_json<>&]: Assertion `m_it.array_iterator != m_object->m_value.array->end()' failed.
Аварийный останов (стек памяти сброшен на диск)

Как заставить json.hpp работать?

**Comment by Kolsha** [comment]
Здравствуйте. Проверьте, что приходит валидный json ответ и парсится правильно. Возможно ВК что-то обновили в ответе, если ответ корректный, попробуйте взять последнюю версию json.hpp из репозитория автора.

**Comment by lexasub** [comment]
ошибка в этой функции - info.begin().value() не пашет
bool VK::Client::check_access(){
    json jres = call("users.get", "");
    if(jres.find("error") != jres.end()){
        this->clear();
        return false;
    }
    try{
        json info = jres.at("response").get<json>();

        std::cout << (jres.find("error")!= jres.end());
        //info = info.begin().value();
        //user.parse(info);
    }
    catch(...){
        this->clear();
        return false;
    }

    return true;
}

**Comment by Kolsha** [comment]
Проверил у себя, с той же версией, все прекрасно работает.

**Comment by lexasub** [comment]
а как аутентифицироваться используя api - key(или как он там называется)

**Comment by Kolsha** [comment]
access_token. 
`api.auth("", "", "acces_token_here")`

**Comment by lexasub** [comment]
#include "vk_api/api.h"

int main(void)
{
VK::Client api;
api.auth("", "", TOKEN);
return 0;
}
вылетает:
json.hpp:8190: nlohmann::basic_json<ObjectType, ArrayType, StringType,
BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType,
AllocatorType, JSONSerializer>::iter_impl<U>::reference
nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType,
NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType,
JSONSerializer>::iter_impl<U>::operator*() const [with U =
nlohmann::basic_json<>; ObjectType = std::map; ArrayType = std::vector;
StringType = std::__cxx11::basic_string<char>; BooleanType = bool;
NumberIntegerType = long int; NumberUnsignedType = long unsigned int;
NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer =
nlohmann::adl_serializer; nlohmann::basic_json<ObjectType, ArrayType,
StringType, BooleanType, NumberIntegerType, NumberUnsignedType,
NumberFloatType, AllocatorType, JSONSerializer>::iter_impl<U>::reference =
nlohmann::basic_json<>&]: Assertion `m_it.array_iterator !=
m_object->m_value.array->end()' failed.
Аварийный останов (стек памяти сброшен на диск)
gdb-хой не умею пользоваться.


2017-11-08 4:29 GMT+00:00 Nikolay Ovchinnikov <notifications@github.com>:

**Comment by lexasub** [comment]
TOKEN определен


2017-11-09 14:42 GMT+00:00 lexa kop <lexakopp2212@gmail.com>:

**Comment by lexasub** [comment]
после обновления json.hpp:
lohmann::detail::iter_impl<BasicJsonType>::reference nlohmann::detail::iter_impl<BasicJsonType>::operator*() const [with BasicJsonType = nlohmann::basic_json<>; nlohmann::detail::iter_impl<BasicJsonType>::reference = nlohmann::basic_json<>&]: Assertion `m_it.array_iterator != m_object->m_value.array->end()' failed.
Аварийный останов (стек памяти сброшен на диск)

**Comment by lexasub** [comment]
вот как собираю: g++ main.cpp -l curl -l pthread -s "vk_api/api.cpp" -s "vk_api/attachment.cpp" -s "vk_api/messages.cpp"
