### ISSUE TITLE
Назначение функций

### ISSUE THREAD

**Issue by reserfodium** [Kolsha/VK#3]
Здравствуйте!

В вашем коде в пространстве имен VK, в класс Utils есть функции _urlencode_, _char2hex_, _CURL_WRITER_. Расскажите, пожалуйста, для чего нужны эти функции.

**Comment by Kolsha** [comment]
http://php.net/manual/ru/function.urlencode.php
http://www.online-toolz.com/tools/text-hex-convertor.php
CURL_WRITER читает данные приходящие от curl и пишет их в строку.
