### ISSUE TITLE
Задержки при получении ответа

### ISSUE THREAD

**Issue by Bawabawa01** [Kolsha/VK#5]
Здравствуйте. Моя программа использует в цикле users.get с нужными параметрами и выводит время онлайна, платформу и тд. пользователя с задержкой 5 сек. после каждого запроса. И временами эти 5 секунд превращаются в ~25 сек. То есть просто ответа нет от VK. Я хоть и добавил авторизацию по access_token до входа в цикл, но это не помогло. Как нужно правильно "авторизовать" программу, чтобы не было задержек на протяжении дня работы программы? И разве ВК клиенты не так работают, постоянно отправляя и получая api методы?

**Comment by Kolsha** [comment]
Проверьте свое интернет соединение, попробуй другие ключи клиента. Возможно сам ВК ограничивает.

**Comment by Kolsha** [comment]
Думаю Вам стоит потестировать в вк консоли https://vk.com/dev/users.get
Если там скорость быстрее, то стоит обратиться в поддержку вк. Код достаточно быстро отрабатывает. Если у Вас есть сомнения, предоставьте бенчмарки.
