### ISSUE TITLE
Ошибка компоновки в Visual Studio 2019

### ISSUE THREAD

**Issue by GladValakas228** [Kolsha/VK#8]
Библиотека libcurl подключена.пример работает.

Ошибка	LNK2001	неразрешенный внешний символ ""public: virtual bool __cdecl VK::Attachment::User::parse(class nlohmann::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::char_traits,class std::allocator >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::adl_serializer> const &)" (?parse@User@Attachment@VK@@UEAA_NAEBV?$basic_json@Vmap@std@@vvector@2@V?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@nlohmann@@@nlohmann@@@z)"

Ошибка	LNK2001	неразрешенный внешний символ ""public: __cdecl VK::Client::Client(class std::basic_string<char,struct std::char_traits,class std::allocator >,class std::basic_string<char,struct std::char_traits,class std::allocator >,class std::basic_string<char,struct std::char_traits,class std::allocator > (__cdeclconst)(class std::basic_string<char,struct std::char_traits,class std::allocator > const &),class std::basic_string<char,struct std::char_traits,class std::allocator > (__cdeclconst)(void))" (??0Client@VK@@QEAA@V?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@0Q6A?AV23@AEBV23@@ZQ6A?AV23@XZ@Z)"

Ошибка	LNK1120	неразрешенных внешних элементов: 2

**Comment by Kolsha** [comment]
> пример работает.
Не совсем понял, в чем проблема.
Покажите код.

**Comment by GladValakas228** [comment]
#include <iostream>
#include "api.h"

#include <curl/curl.h>
#pragma comment(lib,"libcurl.lib")


int main()
{
VK::Client api;
}

**Comment by GladValakas228** [comment]
пример Curl работает

CURL* curl_handle;
	CURLcode res;

	curl_handle = curl_easy_init();
	if (curl_handle)
	{
		// задаем  url адрес
		curl_easy_setopt(curl_handle, CURLOPT_URL, "http://www.cyberforum.ru");
		// выполняем запрос
		res = curl_easy_perform(curl_handle);
		// закрываем дескриптор curl
		curl_easy_cleanup(curl_handle);
	}

**Comment by ghost** [comment]
Проблема была в том, что библиотека лежала в папке src/.Перетащил все файлы из этой папки в проект в VS 19 и все заработало.
